name: Ruff

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    container:
      image: swepy/ruff:latest
      options: --user root
    steps:
      - uses: SWEPY-org/ruff@trunk
        with:
            project_path: 'tests/ruff_project'
